openapi: 3.0.0
info:
  title: Test
  description: Swagger test
  version: '1.0'
  termsOfService: 'urn:tos'
  # contact: {mercurievv@gmail.com}
#  license:
#    name: Apache 2.0
#    url: 'http://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: https://ololo.com/api


paths:
  /test:
    get:
      tags:
        - healthchecks
      operationId: getTest
      summary: run test

      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestResult'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden


components:
  schemas:

    TestResult:
      type: object
      properties:
        test_id:
          type: string
          enum:
            - id1
            - id2
      required:
        - test_id
