name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run clean, tests, build and publish to sonatype
      run: sbt clean;compile;test;publish
      env:  
        OSS_SONATYPE_LOGIN: ${{ secrets.OSS_SONATYPE_LOGIN }}
        OSS_SONATYPE_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
